// ATLSpaceShipSvr.idl : IDL source for ATLSpaceShipSvr
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLSpaceShipSvr.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

    [
        object,
        uuid(692D03A4-C689-11CE-B337-88EA36DE9E4E),
        dual,
        helpstring("IMotion interface")
    ]
    interface IMotion : IDispatch
    {
	     HRESULT Fly();
		 HRESULT GetPosition([out,retval]long* nPosition);
	};

    [
        object,
        uuid(692D03A5-C689-11CE-B337-88EA36DE9E4E),
        helpstring("IVisual interface")
    ]
    interface IVisual : IUnknown
    {
	        HRESULT Display();
    };

[
	object,
	uuid(45896187-46FF-4A07-A9DC-557377380535),
	dual,
	nonextensible,
	helpstring("IClassicATLSpaceship Interface"),
	pointer_default(unique)
]
interface IClassicATLSpaceship : IDispatch{
    [id(1), helpstring("method CallStarFleet")] HRESULT CallStarFleet([in] FLOAT fStarDate, [out,retval] BSTR* pbstRecipient);
};
[
	uuid(F5FD4043-22AE-470D-8C43-1AC904D2E8E0),
	version(1.0),
	helpstring("ATLSpaceShipSvr 1.0 Type Library")
]
library ATLSpaceShipSvrLib
{
	importlib("stdole2.tlb");
	[
		uuid(E485E21E-A23C-413F-A93B-909318565113),
		helpstring("ClassicATLSpaceship Class")
	]
	coclass ClassicATLSpaceship
	{
		[default] interface IClassicATLSpaceship;
	};
};
